version: '3'
services:
  oboxui:
    build:
      context: ./ui
      dockerfile: Dockerfile.ui
    image: yandriievskyi/obox:ui
    volumes:
      - ./ui:/usr/src/app
      - /usr/src/app/node_modules
    env_file: 
      - .env
    ports:
      - "8080:8080"
  oboxbackend:
    build:
      context: ./server
      dockerfile: Dockerfile.express
    image: yandriievskyi/obox:server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
     - "${PORT}:3000"
