version: '3'
services:
  oboxbackend:
    build:
      context: ./server
      dockerfile: Dockerfile.express
    image: yandriievskyi/obox:server
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING} 
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
    ports:
      - "3000:3000"
  oboxui:
    build:
      context: ./ui
      dockerfile: Dockerfile.ui
      args:
        - VITE_API_URL=${API_URL}
    image: yandriievskyi/obox:ui
    volumes:
      - ./ui:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_API_URL=${API_URL}
    ports:
      - "8080:8080"
