version: '3'
services:
  oboxui:
    build:
      context: ./ui
      dockerfile: Dockerfile.ui
      args:
        - VITE_API_URL=${API_URL}
    image: yandriievskyi/obox:ui
    volumes:
      - ./ui:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_API_URL=${API_URL}
    ports:
      - "8080:8080"
  oboxbackend:
    build:
      context: ./server
      dockerfile: Dockerfile.express
    image: yandriievskyi/obox:server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=${PORT}
    ports:
      - "3000:3000"
