FROM --platform=linux/amd64 node:16.20.2-buster-slim
WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm install 
COPY . .
RUN npm install -g ts-node
EXPOSE 3000
CMD ["sh", "-c", "if [ \"$NODE_ENV\" = 'development' ]; then npm run dev; else npm run build && npm run start; fi"]