FROM --platform=linux/amd64 node:16.20.2-buster-slim
WORKDIR /usr/src/app
ARG PORT
ARG DB_CONNECTION_STRING
ARG JWT_SECRET
ARG REFRESH_SECRET
ENV PORT=$PORT
ENV DB_CONNECTION_STRING=$DB_CONNECTION_STRING
ENV JWT_SECRET=$JWT_SECRET
ENV REFRESH_SECRET=$REFRESH_SECRET
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE $PORT
CMD ["sh", "-c", "if [ \"$NODE_ENV\" = 'development' ]; then npm run dev; else npm run build && npm run start; fi"]