FROM --platform=linux/amd64 node:20.15.0-buster-slim
WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm install 
COPY . .
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build
EXPOSE 8080
CMD ["npm", "run", "dev"]
