name: Continuous Integration

on:
  pull_request:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  run-tests:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Run tests
      run: echo "Tests passed"

