name: Continuous Integration

on:
  pull_request:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  API_URL: ${{ secrets.API_URL }}
  PORT: ${{ secrets.API_PORT }}
  DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: sudo apt-get update && sudo apt-get install docker-compose -y

  run-tests:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Run tests
      run: echo "Tests passed"

