name: Deploy

on:
  workflow_dispatch:
    inputs:
      deploy_ui:
        description: 'Deploy UI'
        required: true
        default: 'true'
        type: boolean
      deploy_backend:
        description: 'Deploy Backend'
        required: true
        default: 'true'
        type: boolean

run-name: "Deploy: ${{ github.event.inputs.deploy_ui === 'true' && 'UI' }} ${{ github.event.inputs.deploy_backend === 'true' && 'Backend' }}"

env:
  RENDER_DEPLOY_HOOK_UI: ${{ secrets.RENDER_DEPLOY_HOOK_UI }}
  RENDER_DEPLOY_HOOK_BACKEND: ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  set-run-name:
    runs-on: ubuntu-latest
    outputs:
      run-name: ${{ steps.set-run-name.outputs.run-name }}
    steps:
      - name: Set run name
        id: set-run-name
        run: |
          RUN_NAME="Deploy"
          if [ "${{ github.event.inputs.deploy_ui }}" == "true" ] && [ "${{ github.event.inputs.deploy_backend }}" == "true" ]; then
            RUN_NAME="Deploy UI & Backend"
          elif [ "${{ github.event.inputs.deploy_ui }}" == "true" ]; then
            RUN_NAME="Deploy UI"
          elif [ "${{ github.event.inputs.deploy_backend }}" == "true" ]; then
            RUN_NAME="Deploy Backend"
          fi
          echo "::set-output name=run-name::$RUN_NAME"

  update-run-name:
    runs-on: ubuntu-latest
    needs: set-run-name
    steps:
      - name: Update the deploy workflow run name
        run: |
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} \
            -d "{\"display_title\":\"${{ needs.set-run-name.outputs.run-name }}\"}"

  # deploy-ui:
  #   runs-on: ubuntu-latest
  #   needs: update-run-name
  #   if: github.event.inputs.deploy_ui == 'true'

  #   steps:
  #   - name: Trigger Render deploy for UI
  #     run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_UI }}

  # deploy-backend:
  #   runs-on: ubuntu-latest
  #   needs: update-run-name
  #   if: github.event.inputs.deploy_backend == 'true'

  #   steps:
  #   - name: Trigger Render deploy for Backend
  #     run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}
